function(make_mod)
    get_filename_component(module ${CMAKE_CURRENT_LIST_DIR} NAME)
    set(moduleTest ${module}Test)
    add_library(${module} ${mod_srcs})
    target_compile_options(${module} PRIVATE -Wall -Wextra)
    add_library(${moduleTest} ${mod_test_srcs})
    target_compile_options(${moduleTest} PRIVATE -Wall -Wextra)
    target_link_libraries(${moduleTest} ${module})
endfunction(make_mod)

function(link_against lib)
    get_filename_component(module ${CMAKE_CURRENT_LIST_DIR} NAME)
    target_link_libraries(${module} ${})
endfunction(link_against lib)
